name: Trigger Netlify Build
on:
  schedule:
    # Run at 0115 daily
    - cron: '15 1 * * *'
jobs:
  build:
    name: Request Netlify Webook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f430cd9560aaa42ace64366